### ISSUE TITLE
Is adjoint method implemented for Adams and other adaptive time-stepping solvers?

### ISSUE THREAD

**Issue by ibulu** [jacobjinkelly/easy-neural-ode#1]
Really great work! I am wondering whether adjoint method is implemented for adaptive-stepping solvers such as Adams and others in your repo.

**Comment by jacobjinkelly** [comment]
Thanks! Currently the adjoint method is only implemented for `dopri5` adaptive and `rk4` fixed-grid [here](https://github.com/jacobjinkelly/easy-neural-ode/blob/master/lib/ode.py#L1708-L1716). We found these solvers to be the fastest in wall-clock time, so these were the only solvers we used during training (hence the only ones we implemented a backward pass for via the adjoint method).

The adjoint method hooks into JAX's AD via `defvjp` (you can have a look at the JAX docs and code for `custom_vjp`, `defvjp`).  I would recommend looking at how the adjoint is defined for `_dopri5_odeint` using `_odeint_fwd` and `_odeint_rev` as an example to go off of. The only change you need to make to define the adjoint for different solvers is to `defvjp` using a `fwd` and `bwd` function which calls the [appropriate solver](https://github.com/jacobjinkelly/easy-neural-ode/blob/master/lib/ode.py#L1617). In fact, you can use different solvers for the forward and backward pass if you wanted to!

Let me know if that makes sense, or anything else I can help with.

**Comment by ibulu** [comment]
sounds good. I just tried the odeint_grid function. it is returning a solution only at two time points regardless of t.

**Comment by jacobjinkelly** [comment]
Yes, unfortunately it's a bit trickier to create a grid for multiple time points. An implementation is in [torchdiffeq](https://github.com/rtqichen/torchdiffeq/blob/master/torchdiffeq/_impl/solvers.py#L59-L72) but I wasn't able to port it to JAX.

**Comment by ibulu** [comment]
ohh no worries. I should have read the source code mode carefuly
