### ISSUE TITLE
Error on trying to run the experiments

### ISSUE THREAD

**Issue by avik-pal** [jacobjinkelly/easy-neural-ode#2]
I am trying to run the experiments `mnist.py` and `ffjord_mnist.py` however I encounter a few runtime errors:

1. `mnist.py`
```
Traceback (most recent call last):
  File "mnist.py", line 684, in <module>
    run()
  File "mnist.py", line 526, in run
    forward, model = init_model()
  File "mnist.py", line 275, in init_model
    ode_dim = jnp.prod(ode_shape[1:])
  File "/home/avik-pal/.local/lib/python3.7/site-packages/jax/numpy/lax_numpy.py", line 1797, in reduction
    _check_arraylike(name, a)
  File "/home/avik-pal/.local/lib/python3.7/site-packages/jax/numpy/lax_numpy.py", line 297, in _check_arraylike
    raise TypeError(msg.format(fun_name, type(arg), pos))
TypeError: prod requires ndarray or scalar arguments, got <class 'tuple'> at position 0.
```

2. `ffjord_mnist.py`
```
Traceback (most recent call last):
  File "ffjord_mnist.py", line 730, in <module>
    run()
  File "ffjord_mnist.py", line 645, in run
    batch = next(ds_train)[0]
TypeError: '_IterableDataset' object is not an iterator
```

I am using the CPU version of jax. Would it be possible to get the version bounds for the dependencies?

**Comment by avik-pal** [comment]
cc @jacobjinkelly @jessebett

**Comment by jacobjinkelly** [comment]
Hi @avik-pal, thanks for making this issue! I'm a little busy right now but I can followup this upcoming weekend

**Comment by avik-pal** [comment]
@jacobjinkelly were you able to figure this out?

**Comment by jacobjinkelly** [comment]
Hi @avik-pal, sorry for dropping the ball on this! Could you try `jax==0.1.64` and `jaxlib==0.1.45`? I'm basing this off of the original code we used for the experiments which is in this [fork of jax](https://github.com/jessebett/jax/tree/hk-nodes). If that doesn't work, let me know and I'm happy to dig deeper.

**Comment by qsh-zh** [comment]
@avik-pal I encounter the same errors. Do you figure this out? @jacobjinkelly  Thanks for your open source project. However, changing the version of jax does not work. Could you help report your environment setup?

**Comment by jacobjinkelly** [comment]
Hi @avik-pal @qshzh I managed to figure it out, all of the fixes are pushed. I got the code to run with the latest version of JAX. Let me know if that works for you!

**Comment by avik-pal** [comment]
@jacobjinkelly yes it works now. Thanks a lot!
