### ISSUE TITLE
toy examples

### ISSUE THREAD

**Issue by pharringtonp19** [jacobjinkelly/easy-neural-ode#4]
Are there any toy examples/tutorials available? I would be interested in applying this approach to other datasets

**Comment by jacobjinkelly** [comment]
Yes! I think [this file](https://github.com/jessebett/jax/blob/hk-nodes/examples/nodes_toy.py) is a toy example I used. There are some other files on that branch that might be useful too for toy problems. The example gif on this repo and in Figure 1 of the paper is learning the function x^3, which should be a similar setup to the linked script.

**Comment by pharringtonp19** [comment]
@jacobjinkelly Thanks!

**Comment by jacobjinkelly** [comment]
Closing this for now, but feel free reopen this one or make a new issue if you have any other questions! :D
